version: '3.5'

services:
  db:
    image: mariadb:10.6
    restart: always
    container_name: MARIADB
    env_file:
      - db.docker.env
    ports:
      - '3306:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
    - .env
    environment:
      - DB_HOST=db