version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: POSTGRES
    env_file:
      - .docker.env
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .docker.env