name: Setup Node.js

on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - workflow_run

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
